### ISSUE TITLE
Mismatch between actual and reported migrations on smidig2010.no

### ISSUE THREAD

**Issue by jhannes** [smidig/smidig-conference#101]
Modify the smidig2010 production database to include all migrations that have actually been run on that database, so that heroku db:pull smidig2010 + rake db:migrate works.

How to reproduce:
- heroku db:pull --app smidig2010
- rake test
  - Message: You have X pending migrations
- rake db:migrate

Shows the message:

==  AddCommentsTable: migrating ===============================================
-- create_table(:feedback_comments)
rake aborted!
An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: table "feedback_comments" already exists: CREATE TABLE "feedback_comments" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "talk_id" integer, "comment" varchar(255))

**Comment by oma** [comment]
added the existing migration timestamp to schema_migrations. solved.
