### ISSUE TITLE
Tabs need to be converted to spaces during commit

### ISSUE THREAD

**Issue by sjbrodwall** [smidig/smidig-conference#114]

**Comment by oma** [comment]
first of all, this is something each developer have to set up locally. Each should spend time setting this up, else we waste others time, getting shit from github.

**Comment by sjbrodwall** [comment]
What's second of all?

**Comment by oma** [comment]
smartass, hehe. I've set this up with both RubyMine and TextMate. So if I touch the file, tabs and trailing spaces will be removed/replaced. If you get tabs from a git pull, notify the offender :)
