### ISSUE TITLE
receipt

### ISSUE THREAD

**Issue by oma** [smidig/smidig-conference#116]
create receipt page. Simple, with 25% mva. like flytoget or nsb.
1. show this after redirect back from paypal
2. show receipt-link for paid users at profile page
## NSB kvitteringseksempel

KJØPSINFORMASJON
Navn: OLE MORTEN AMUNDSEN
Adresse: ETTERSTADGATA 16, 0658
Referansenr: 102332379
Betalingsform: VISA ############6290
Billetten hentes på: Stasjon/automat
Telefonnummer: 99627200
Plassinformasjon:
09.03.2011 OSLO S - LARVIK 05:37 - 07:51 (02:14)
Ingen bestemt plass
09.03.2011 LARVIK - PORSGRUNN 07:55 - 08:18 (00:23)
Ingen bestemt plass
Antall reisende: 1 Voksen

Total Pris: 199.00
Mva: 8.00% Gr.lag: 184.26 Mva kr: 14.74
NSB AS Org nr. 984661177 MVA

Refusjon:
Minipris: Gjelder kun angitt(e) togavgang(er). Ingen refusjon eller endring.

VIKTIG INFORMASJON
       - Ta en utskrift av bekreftelsen eller noter deg referansenummeret.
       - Ved uthenting av billett på billettautomat må referansenummer og telefonnummer oppgis.
       - Denne utskriften er ikke gyldig som billett.

Mer informasjon om betingelser og din reise finner du på nsb.no

NSB AS ønsker deg en god reise!

NSB Kundesenter: 815 00 888

---

**Comment by sjbrodwall** [comment]
Apparently HTML is an acceptable format, according to the retningslinjer we got from the (I think) revisor.  So no messing around with Prawn etc. is necessary.
