### ISSUE TITLE
Error on RSS-feed for lightning talks

### ISSUE THREAD

**Issue by knuthaug** [smidig/smidig-conference#119]
By following the link on http://smidig2011.no/talks for RSS-feeds for suggested lightning talks, which directs you to  http://smidig2011.no/talks.rss you get Herokus "Something went wrong"-page with no further information. And no rss-feed :-(

**Comment by ivarconr** [comment]
Nil handling not up to speed!

**Comment by ivarni** [comment]
This is only an issue when there are no talks registered. Since we have some for 2011 now I'll remove the "must" flag. This should be fixed before 2012 though.

**Comment by jhannes** [comment]
Fixed
