### ISSUE TITLE
Still only early-bird price on signup page

### ISSUE THREAD

**Issue by knuthaug** [smidig/smidig-conference#142]
The signup page still lists (as of writing, October 17th) only the early bird-price if you register before October 14th. This is not such a good deal when you need to aquire a time machine first to take advantage of it. 

Two possible solutions: either update the page text and pricing info to non-early bird price (so I can pitch my boss on registering) or give me the number of the Doctor, so I can go back and register on friday. 

Up to you :-)

**Comment by bodil** [comment]
Sorry, the TARDIS won't let you cross your own timeline, remember, so I think we'll have to settle for updating the page. :)

**Comment by jhannes** [comment]
If you register now, you'll still get the early bird price. The system is
automatic. Ssssshhhh, don't tell anyone.

~Johannes

**Comment by ivarconr** [comment]
The system supports time-travel. Register fast and you will still get the price of the past.. Not for long though!
