### ISSUE TITLE
Fix javascript madness on program page

### ISSUE THREAD

**Issue by karianne** [smidig/smidig-conference#152]
As a user wanting to browse interesting workshops
I want the back button to take me back to the workshops tab on the program page after I've looked at an abstract
So that I won't have to click the workshop tab every time I've used the back button

**Comment by ivarconr** [comment]
Thanks for spotting this. Resolved with #9f59d0c0819fbe6900ce356a97fe7bb423836c73 and #24d21c4968ae490d412f76a9691af455e5ae146f.
