### ISSUE TITLE
Sponsor logo CSS bug

### ISSUE THREAD

**Issue by matsringstad** [smidig/smidig-conference#154]
Sponsorlogoene vises ikke i Chrome hos meg. Fungerer fint i Firefox. Ser ut som det er CSS'en som er problemet. Se epost sendt 01.07.2012 ca kl 14:00 til dev@smidig og smidig-lista med screenshots.

**Comment by ivarconr** [comment]
Siden dette virker hos Mats i incognito avventer vi med denne feilen inntil andre rapporterer et tilsvarende problem.

**Comment by ivarni** [comment]
Samme problem hos meg, Chrome (v20.0.1132.47) på OSX 

Bilder vises om jeg kjører $("a").removeClass("sponsor-link") i console

**Comment by ivarconr** [comment]
Takk, dette var til stor hjelp!! Fixed by removing the clasname and use element type instead..
