### ISSUE TITLE
Som en idiot fra Pors, vil jeg ha tema å velge fra, slik at jeg ikke blir stoppet når jeg registrerer en lyntale

### ISSUE THREAD

**Issue by anderssv** [smidig/smidig-conference#18]
Må legges inn stamdata med tema for registrering av lyntaler

**Comment by jhannes** [comment]
Kan gjøres på http://stagingsmidig.heroku.com/topics/new (eller tilsvarende i produksjon). Nå er det bare å komme opp med temaene...
