### ISSUE TITLE
Error with paypal on staging

### ISSUE THREAD

**Issue by anderssv** [smidig/smidig-conference#20]
Stopped when trying to register and redireted to Paypal. Message:

This invoice has already been paid. For more information, please contact the merchant.

**Comment by oc** [comment]
I second this. "This invoice has already been paid. For more information, please contact the merchant."

**Comment by ivarconr** [comment]
I also experience the described issue.

**Comment by ivarconr** [comment]
Possible cause: We use "paypal invoice" id based on id field in the registrations table Because we have a new environment and the registrations table in staging is basically empty we reuse an earlier invoice number. 

Possible fix: increase the auto_increment counter to give values > 432.

**Comment by ivarconr** [comment]
Proposed solution solved the issue.
