### ISSUE TITLE
Getting ready for Rails 3

### ISSUE THREAD

**Issue by jhannes** [smidig/smidig-conference#22]
I tried converting the application to Rails 3 and found a few issues that we might as well address in the application before we convert:
- All files must have encoding UTF-8 (not UTF-8 BOM as today)
- Some of the unused stuff causes problems and might as well be removed: lib/tasks/cucumber, lib/tasks/rspec
- IMPORTANT: Helpers can no longer return HTML - this HTML will be escaped. We need to find a new way of doing this.

There are a few other issues as well, these don't really belong to this ticket, but I haven't got anywhere else to put them:
- authlogic doesn't seem to work very well with Rails 3
- The fields_for forms helper doesn't seem to work. At all!

**Comment by oma** [comment]
We've (I) been down this path, rails 3 is a Mayor release. We won't convert Smidig2010. Maybe Smidig2011? Some comments:
- helpers may return html if they mark it html_safe (rails3 specific).
- yes, clean ups are needed in any case!
- authlogic works, I think our use of it is the problem in rails3.

**Comment by oc** [comment]
I'm closing this. We can reopen it for smidig 2011!
