### ISSUE TITLE
Uploading talk attachments

### ISSUE THREAD

**Issue by oc** [smidig/smidig-conference#25]
Uploading of file attachments does not work on heroku (file system is not accesible).

Research paperclips / S3 and other solutions that work with heroku.

**Comment by oma** [comment]
should have some validation of file type or a pending state for uploaded files before they are open to the world. Maybe authorization (view your own only + admins), is sufficient. (ref mail from Sarah)

**Comment by oc** [comment]
http://docs.heroku.com/s3

http://github.com/pedro/paperclip-on-heroku

**Comment by karianne** [comment]
The only file types allowed earlier years have been ppt, pptx and pdf.

**Comment by karianne** [comment]
We have to allow OO Impress file type too.

**Comment by oma** [comment]
The amazon aws S3 keys for the smidig's dev-user is now at at smidig201 on heroku.

**Comment by oma** [comment]
done, some bugs wrt too uploading occurs. seems like there is some paperclip - S3 unstability.... will have to follow up on that one, closing this issue.
