### ISSUE TITLE
Mass mail via filter

### ISSUE THREAD

**Issue by smidig** [smidig/smidig-conference#3]
To limit administration, as an admin I wish to mail groups of participants / speakers information.

(Some of the) groups that should be mailable: unpaid participants, paid-participants, sponsor-tickets, students, arrangers, volunteers, speakers, submitters

**Comment by karianne** [comment]
Yes, yes, a million times yes! This was loads of manual work last year. 

The mass mail thingie should support simple templating (for instance "Hei $navn, vi vil gjerne informere om at ditt foredrag med tittelen $tittel har blitt godkjent til Smidig 2010".

**Comment by jhannes** [comment]
It was pretty difficult to create a general solution, but what we've got as https://github.com/smidig/smidig-conference/blob/master/lib/tasks/infomail.rake seems to be working pretty well for now.
