### ISSUE TITLE
Fjern "Lyntale passer best for..." valgene

### ISSUE THREAD

**Issue by oma** [smidig/smidig-conference#38]
det bør komme frem at det er novice, intermediate, expert. Det bør også være mulighet for å velge "alle"

bør være mer brukerstyrt? legge til tags selv? fortelle hvilket publikum det retter seg mot?

**Comment by knuthaug** [comment]
Savner veldig en "passer for alle" eller lignende. Valgene som er der nå er litt epler og bananer siden man blander "ikker har benyttet smidige metoder" med de som er prosjekt-avhengige.

**Comment by jhannes** [comment]
Vi fjerner dette til fordel for tagging.
