### ISSUE TITLE
caching dynamic content

### ISSUE THREAD

**Issue by oma** [smidig/smidig-conference#42]
use memcached. Follow the instructions at heroku https://docs.heroku.com/memcache and read up on caching in general at heroku ere. https://docs.heroku.com/http-caching

Bonus, a beer of your choice, with KOI as upper price limit.

We'll have to add the memcached addon at heroku. I'll help you if needed.

**Comment by ivarconr** [comment]
I've added cache-control to static info pages, which will make heroku's varnish cache these static pages for one hour.

**Comment by jhannes** [comment]
Performance will be examined from scratch. Close this issue to reduce clutter.
