### ISSUE TITLE
Better status for users regarding invoice and follow up

### ISSUE THREAD

**Issue by anderssv** [smidig/smidig-conference#43]
The current "follow up" status is too narrow. The request is specifically for people that want's an invoice sent. For tracking a minimum would be "To be invoiced".

The user could switch from "Follow up" to "To be invoiced" themselfes by following a link sent to them in a standard follow up mail.

A possible addition could be a "Have been invoiced" status.

**Comment by karianne** [comment]
Don't we have this already in /registrations?

**Comment by jhannes** [comment]
Payments will be redone for 2011. This issue is closed to reduce clutter.
