### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by karianne** [smidig/smidig-conference#46]
I might be the only statistics freak here, but I would like to have some simple statistics for the site to use in marketing and to know more about our users. Examples:
- # users per category (early bird, full price, speaker, organizer, sponsor ticket)
- # users/speakers grouped by company
- # of sponsors
- # of companies having registred participants
- Median/average number of speakers/users per company

This was done last year by a lot of dog-ugly SQL queries, but having them on the site would save a bit of work.

**Comment by cstensholt** [comment]
I would like to export source data to an excel sheet and make pivot tables. That is more flexible for the statistics freak.

**Comment by karianne** [comment]
Some of the most useful statistics compares with earlier years, for instance how many people a given company sent last year vs now, how many people (in %) that also attended last year, etc)

**Comment by jhannes** [comment]
Here's how you can make custom queries as reports:

http://github.com/smidig/smidig-conference/commit/c3dff56652f2f6e5d80f10fa0e2dcc88f3c1b76b

**Comment by karianne** [comment]
Implemented users, speakers and accepted speakers per company.

**Comment by jhannes** [comment]
Statistics will come up again as needs arise. This issue is closed to reduce clutter.
