### ISSUE TITLE
Sponsors in the app

### ISSUE THREAD

**Issue by karianne** [smidig/smidig-conference#47]
It would be very nice if we had sponsors as an entity in the application. They are already "mentioned" in the application with the sponsor tickets, but here it should be possible to register sponsor tickets to a sponsor, so that you could have less manual work with approval and checking whether the sponsor had any sponsor tickets left etc. The upcoming (I hope) mail filter functionality would then also have the possibility to send out mail to all sponsors, something that is done quite a few times.

**Comment by jhannes** [comment]
This may come up again, but for now, the issue is closed to reduce clutter.
