### ISSUE TITLE
Download archive with all slides for use in conference rooms

### ISSUE THREAD

**Issue by karianne** [smidig/smidig-conference#48]
Last year, it was a long manual and error prone process to download all the presentation slides and put them in a folder structure, so that it was easy to find the right presentation at the day of the conference. The application already holds the order and rooms of the presentations, so this should be done automatically.

**Comment by jhannes** [comment]
JIT-implementation that we made for the conference is here: https://github.com/smidig/smidig-conference/blob/master/lib/tasks/sort_slides.rake

This will probably be sufficient for 2011 as well.
