### ISSUE TITLE
Link to faktueringsregnearket is wrong

### ISSUE THREAD

**Issue by cstensholt** [smidig/smidig-conference#52]
The link to Faktueringsregnearket from http://smidig2010.no/registrations is wrong. It should be https://spreadsheets.google.com/ccc?key=0AhricdnsaMlJdGEzNVZWX0Q1V041LTdOYjVCWW5fVFE&hl=en&pli=1#gid=0

**Comment by oma** [comment]
denne oppgaven er en no-brainer. fin måte å få opp miljøet og prodsette sin første bugfix :) Denne overlater jeg til .. deg som leser dette!

**Comment by oma** [comment]
altså, gitt at du er interessert i å lære litt om ruby og hvordan deploye ruby-apper. Du må ha ruby, git og heroku oppe å kjøre (se README).

**Comment by oma** [comment]
er gjort i samarbeid med christian
