### ISSUE TITLE
Creation of new user fails when email address has leading space

### ISSUE THREAD

**Issue by karianne** [smidig/smidig-conference#53]
Error message is not very helpful - should be fixed

**Comment by oma** [comment]
bug, really? done, stripping whitespaces now, if user is retar... er, hold my horses, hehe. good night!

**Comment by karianne** [comment]
This was an actual mistake I made. I received a list over nine users someone wanted me to enter into the system, and accidentally copy-pasted in the email address with a leading space. Easy to do, hard to find out what was wrong from the error message "this does not look like an e-mail address". There are probably more retarded people like me out there. ;)

**Comment by oma** [comment]
haha :)
