### ISSUE TITLE
Min påmelding lite synlig

### ISSUE THREAD

**Issue by oma** [smidig/smidig-conference#55]
Som innlogget bruker synes jeg det er lite tydelig hvor "Min påmelding" er. ja, den er til venstre over logoen, men det skjønte jeg ikke med en gang.

**Comment by karianne** [comment]
Flere som har lett etter denne, ja...

**Comment by oma** [comment]
Forslag, bytte ut dynamisk innhold, ha "meld deg på" over logoen hele tiden, samt "Min påmelding" opp til høyre. Så legger vi logg ut/logg inn her på min påmelding-siden, vi redirecter stadig til logg innsiden der man krever bruker logget inn. Ikke noe poeng med dynamisk innlogget/ikke innlogget innhold

**Comment by ivarconr** [comment]
oma's forslag implementert,
