### ISSUE TITLE
Betaling. Kommunisere at adresseinformasjonen du legger inn må stemme med det du har registrert hos paypal

### ISSUE THREAD

**Issue by oma** [smidig/smidig-conference#56]
Lennart slet med å få betalt og vi fant til slutt ut at det var fordi adressen han registrerte, ikke matchet kortet (han har flyttet). Det er ikke kommunisert at disse må matche. 

Vi burde evt hatt en betalingsadresseboks, her huker man av for "samme som min adresse", f.eks.

**Comment by jhannes** [comment]
We don't really know how to fix this. Closed.
