### ISSUE TITLE
TEMA lyntale.  "tema kommer snart" bør ... komme snart!

### ISSUE THREAD

**Issue by oma** [smidig/smidig-conference#58]
start enkelt! statisk liste
deretter: dynamisk? hvordan komme med forslag?

**Comment by knuthaug** [comment]
Denne begynner vel å haste litt når det når har kommet inn over over 40 forslag?

**Comment by karianne** [comment]
Fjernet denne muligheten. Når vi ikke har gjort det ennå, så er det for sent.
