### ISSUE TITLE
automatic scaling. (how awesome is that!)

### ISSUE THREAD

**Issue by oma** [smidig/smidig-conference#59]
This is KISS. 

As the credit card owner, we should limit from min 2, max 4 dynos. If we need more, solve the caching 'issues' first:)

http://github.com/ddollar/heroku-autoscale

Need details? contact oma.
heard of it here: 
http://support.newrelic.com/discussions/support/3666-automatic-scaling-scheduled-or-by-peak-traffic-with-the-new-relic-heroku-combo-how

**Comment by jhannes** [comment]
Will look into this again if it becomes an issue again. Closed for now to reduce clutter.
