### ISSUE TITLE
Send automatic email when "special user" is confirmed

### ISSUE THREAD

**Issue by karianne** [smidig/smidig-conference#63]
We have to send manual emails when we confirm special users (like sponsors, other organizers and volunteers). This should be automatic to avoid manual work.

**Comment by jhannes** [comment]
Should the text of the email be hard coded, or should you be able to edit it when you confirm the user?

**Comment by karianne** [comment]
Hard coded is fine.

**Comment by jhannes** [comment]
We might implement this, but left for now.
