### ISSUE TITLE
Limit the # of abstracts each speaker can submit

### ISSUE THREAD

**Issue by karianne** [smidig/smidig-conference#65]
As a member of the program committee
I want to limit the # of abstracts each speaker can submit
So that I don't have to wade through quite so many abstracts from a single speaker

This limit should ideally be configurable.

**Comment by jhannes** [comment]
We have never ended up _accepting_ more than one talk per speaker. I have a solution that will make each user able to submit as many talks as possible, but only allows the user to have one active talk at a time. Could this work as the solution?

**Comment by karianne** [comment]
What if the speaker has two abstracts, want to talk about one and thus has this one active, but the program commitee wants the other one on the program?

**Comment by jhannes** [comment]
My patch has the talks be radio buttons for the user, but checkboxes for the committee, if that makes any sense. The committee is free to accept talks independent of the preferences of the speaker.

**Comment by karianne** [comment]
If the committee can choose abstracts independently of the preference of the speaker, then how does that limit the # of abstracts the committee has to read? IMO, your patch fixes a different problem: Knowing what talk the speaker would like to do the most, and choosing that one when he/she has two talks we want to put on the program.

**Comment by jhannes** [comment]
Yes: It's a different fix to the same problem and does not provide the requested functionality. I hoped it was good enough, but then I'll leave this issue for someone else to fix. :-)

**Comment by cstensholt** [comment]
I think this is solved by #77

**Comment by karianne** [comment]
Disagree. The purpose is to get the users to submit fewer abstracts so you have to read fewer (and also so people will write three really good abstracts, rather than five mediocre ones).

**Comment by jhannes** [comment]
We will do the program different this year. This issue is closed to reduce clutter.
