### ISSUE TITLE
Automatic email when paying participant is registered, but hasn't paid for X days

### ISSUE THREAD

**Issue by karianne** [smidig/smidig-conference#68]
As an admin
I would like an automatic email to be sent when a paying participant is registered, but hasn't paid for X days
so that I don't have to follow up this myself

Would also be neat to have a field in the registration table with a boolean if this has happened yet or not.

**Comment by jhannes** [comment]
We will look into totally new ways of doing payments. May come up again, but closed for now to reduce clutter
