### ISSUE TITLE
hard limit 500 users

### ISSUE THREAD

**Issue by oma** [smidig/smidig-conference#72]
if user.count > 500
 flash[:error] = "Vi har nådd maksgrensen for påmeldinger, vennligst send oss mail på kontakt@smidig.no så ser vi hva vi får gjort"
 redirect_to => :new

hvorfor bare gjør jeg ikke dette istedenfor å lage issue? dunno...

**Comment by karianne** [comment]
Er det ikke plass til flere enn 500?

**Comment by oma** [comment]
hvilken grense foreslår du? Meningen er å ha en sikring her. Når vi grensen, kan vi ta en vurdering (helst før vi faktisk når den) og endre denne.

**Comment by karianne** [comment]
Jeg vet ikke, jeg aner ikke hvordan konferanselokalene ser ut. Sett 500 som grense du, så tar vi heller en vurdering da, sånn som du sier.

**Comment by ivarconr** [comment]
Dette er nå implementert.

**Comment by ivarconr** [comment]
implemented
