### ISSUE TITLE
RSS feed for all comments

### ISSUE THREAD

**Issue by knuthaug** [smidig/smidig-conference#73]
As an enthusiastic users, I'd like to subscribe to all comments being posted, not only for a given lightning talk.

Feed titles should reflect the title of the lightning talk. See comment of Knut Haug.

**Comment by karianne** [comment]
Hei Knut,

Jeg testet ut dette, men klarer ikke å gjenskape feilen. For eksempel kommentar-feeden til http://smidig2010.no/talks/9 kommer helt fint opp i Google reader, og XML-en ser korrekt ut. Kan du gi meg litt mer informasjon om konkret hva det var som ikke virket for deg?

**Comment by knuthaug** [comment]
Brukerfeil! Jeg antok at feeden jeg abonnerte på var for alle kommentarer, siden den heter "Comments for Smidig 2010 talks" i flertall, og ikke angir tittel på talk den er kommentarer for. Men en kjapp titt på url og koden for dette, viser jo at det slett ikke er tilfellet. My bad. 

Men det betyr da at om man ønsker å følge med på alle kommentarer via rss, må man abonnere på _alle_ feeds? Er samlefeed for kommentarer kanskje en ting å sette på ønskelista for neste versjon? Pluss at tittel for feedene kunne vært bedre. Om jeg abonererer på mer enn en, vil de se helt like ut i leseren.

**Comment by oma** [comment]
Ja... why not. Det er som i alle it-prosjekter mye å gjøre, liten tid og få ressurser, hehe, men lyntalesidene vil ha fokus til helga. 

ISSUE ENDRET: fra "rss feed tom" til "ønsker å abonnere på alle kommentarer"

**Comment by ivarni** [comment]
How should this look on the page? Should we put a "subscribe to all comments" icon on the /talks index page or on each single /talks/x page? Or both?
