### ISSUE TITLE
Delete own abstract

### ISSUE THREAD

**Issue by karianne** [smidig/smidig-conference#76]
As a person who delivered an abstract and regretted it
I would like to be able to delete my own abstracts
So that only abstracts I like will be considered

**Comment by oma** [comment]
You're great at writing these issues, Karianne! Should we delete or disable(hide)?

**Comment by karianne** [comment]
Yeah, I'm a real pain in the ass. ;) About time I start solving some more of these issues too, perhaps? Will forget my newfound Ruby skills if I don't practice. To little time, too much to do...

Don't know if we should delete or disable. I guess disabling would solve the problem of the user, too. Although we might get the problem of people who send in abstracts early and then disables them so people won't read them. This will probably not be a huge problem, though.

**Comment by oma** [comment]
What I was trying to say was: "You are great at writing understandable issues in the form of user stories" :) Lets present it as a "delete", but merely disabling it locally. OK?

**Comment by karianne** [comment]
That's fine.

**Comment by jhannes** [comment]
Since the program might be different in 2011, we will recreate this issue if necessary
