### ISSUE TITLE
Setting a talk to accepted/refused

### ISSUE THREAD

**Issue by karianne** [smidig/smidig-conference#77]
As a member of the program committee
I would like to be able to accept and refuse talks through a GUI interface
So that I won't have to do ugly stuff in the Ruby console and jump through a window in pure frustration

There should be a field "status" on talk with accepted/refused/new, and preferably a list over all talks with status "new" that you can go through and accept/refuse.

**Comment by cstensholt** [comment]
and I would like to do it in the same screen where I accept the speaker so I can accept one talk and reject the other if the user has more than one talk

**Comment by karianne** [comment]
Det jeg ser for meg er en side med liste over alle foredragstitlene med speaker og en radioknapp ved siden av som har verdiene "ny", "akseptert" og "refusert".
Så kan vi sortere på speaker, da får du foredrag av samme speaker rett ved hverandre, slik at det er lett å godkjenne ett og refusere de andre.

**Comment by karianne** [comment]
Denne bør automagisk oppdatere user: sette billettype til early bird/full price dersom alle hans talks er refusert, og sette completed=true på registration dersom han har fått et godkjent foredrag.

**Comment by cstensholt** [comment]
Dette er bedre enn mitt forslag

**Comment by karianne** [comment]
Vil dere også at når man godkjenner en talk, skal alle andre talks av samme speaker automagisk bli refusert?

**Comment by cstensholt** [comment]
Usikker, er kjent med at det praktiseres en taler, kun en lyntale. Med automatikk gjør vi  regelen med kun en lyntale pr. taler nærmest aboslutt. Det er ikke mye arbeid og refusere manuelt heller

**Comment by karianne** [comment]
Okei, da lar jeg være å implementere det.

**Comment by karianne** [comment]
Implemented and deployed.
