### ISSUE TITLE
Error accepting speaker

### ISSUE THREAD

**Issue by cstensholt** [smidig/smidig-conference#78]
User id 51 (Andreas Larsson) and 305 Marcus Ahnve is not accepted as speakers.
Error message: The change you wanted was rejected. Maybe you tried to change something you didn't have access to.

The only difference from other users is that their email is .se. (Anyone whos does not want swedish speakers?)

**Comment by karianne** [comment]
My fault! Dammit. The problem is the phone number validation I thought was more permissive, but I forgot the fact that not all scandinavian phone numbers have 8 digits.. will fix ASAP!

**Comment by karianne** [comment]
Fixed and deployed.

**Comment by karianne** [comment]
Fixed.

**Comment by cstensholt** [comment]
and the speakers are accepted!
