### ISSUE TITLE
Let a speaker see if the talk is accepted or rejected

### ISSUE THREAD

**Issue by cstensholt** [smidig/smidig-conference#80]
As a speaker I want to see if my talks are accepted or rejected on my account page (Min påmelding)

**Comment by karianne** [comment]
Sakset fra mail:
Vil du at bare lyntaleren selv skal se det, eller skal alle se det? Og skal de se det med en gang du godkjenner, eller etter det er sendt ut mail?

**Comment by cstensholt** [comment]
Vil vel foretrekke etter mail da taleren bør være den første som informeres. Hvis det medfører vanskelighet fordi #82 må gjøres først vil jeg foretrekke at det vised på min side og at vi bruker manuell mailutsending

**Comment by jhannes** [comment]
Since the program might be different in 2011, we will recreate this issue if necessary
