### ISSUE TITLE
Send email to speakers after acceptance or rejection

### ISSUE THREAD

**Issue by cstensholt** [smidig/smidig-conference#82]
As an administrator I want to send email to a speaker to tell the speaker that the talk has been accepted or rejected. If the speaker has more than one talk I want to list all the talks in one email, both accepted and rejected talks. After a successful email I should not be able to change the acceptance or rejection and the result should be shown on the talk page and on the speakers account.

**Comment by cstensholt** [comment]
Det hadde også vært fint om administrator kunne legge inn en e-post tittel og  tekst som ble brukt i e-posten. Finnes det også muligheter for fletting? Hei <name> din lyntale <title> er godkjent osv.

**Comment by karianne** [comment]
Ja, det finnes absolutt muligheter for å flette inn navn på vedkommende, tittel etc. Admininterface for å redigere teksten tror jeg vi skal ta i en senere versjon.

**Comment by karianne** [comment]
Implementert.
