### ISSUE TITLE
Student tickets

### ISSUE THREAD

**Issue by karianne** [smidig/smidig-conference#83]
As a student with limited money
I would like to be able to buy tickets at a discounted price
So that I can spend my money on other necessities, like beer.

As a committee member
I want to be able to confirm that people that sign up for student tickets are actually students
So we don't end up subsidising people that gets paychecks.

As a committee member
I would like it to be a limited number of student tickets
So that we won't go bankrupt from subsidising students.

**Comment by cstensholt** [comment]
Til pkt. 2: Holder det ikke at de viser studentbevis ved innsjekking?

**Comment by karianne** [comment]
Tenkte kanskje de kunne scanne studentbevis og sende på mail eller noe... Poenget her var at vi manuelt må "godkjenne" studenter, du bør ikke få studentbillett automagisk.

**Comment by jhannes** [comment]
Jobber med denne nå. Pushet til http://stagingsmidig.heroku.com/users/new?ticket_type=student

**Comment by jhannes** [comment]
http://smidig2010.no/users/new?ticket_type=student
