### ISSUE TITLE
List of participants to ease administration of payments

### ISSUE THREAD

**Issue by cstensholt** [smidig/smidig-conference#88]
As an administrator I want two list of all participants with status "Skal faktureres" and "Har blitt fakturert"  to ease the administration of payments.

This should be an option under Andre søk on the Registrations page.

**Comment by jhannes** [comment]
Will come up again if still an issue in 2011

**Comment by cstensholt** [comment]
Hope this will be solved in one way or another

**Comment by jhannes** [comment]
It will. But we don't know how invoicing will work this year, so there's no point in keeping an issue that refers to 2010 open.

**Comment by jhannes** [comment]
http://smidig2011.no/registrations/invoiced
