### ISSUE TITLE
Support several types of talks

### ISSUE THREAD

**Issue by jhannes** [smidig/smidig-conference#91]
- Workshop
- Lyntale
- Tordentale

**Comment by karianne** [comment]
Rootsconf has this. You might want to steal it from us.

**Comment by jhannes** [comment]
Noen av de mest relevante bitene fra ROOTS:

https://github.com/rootsconf/rootsconf2011/blob/master/db/migrate/20110123185312_create_talk_types.rb
https://github.com/rootsconf/rootsconf2011/blob/master/db/migrate/20110123190506_add_talk_types.rb
https://github.com/rootsconf/rootsconf2011/blob/master/db/migrate/20110126212418_add_type_to_talk.rb
https://github.com/rootsconf/rootsconf2011/blob/master/db/migrate/20110202213037_remove_talk_id_from_talk_type.rb
https://github.com/rootsconf/rootsconf2011/blob/master/db/migrate/20110126212746_add_talk_to_talk_type.rb
https://github.com/rootsconf/rootsconf2011/blob/master/db/migrate/20110202222859_add_duration_to_talk_type.rb
https://github.com/rootsconf/rootsconf2011/blob/master/app/views/talks/_form.html.erb#L52

**Comment by ivarni** [comment]
I can probably take a look at this on thursday

**Comment by ivarni** [comment]
Is there anything that needs to be done with periods and the program after this change? Haven't really had time to look at those parts yet so leaving the issue open for now.

**Comment by ivarni** [comment]
I really need to learn how to aim with this mouse...

**Comment by ivarni** [comment]
Postponing further fixes regarding the program, for signups we just need to register and show talk types

**Comment by ivarni** [comment]
Reopened after conferring with Ivar(1), we need to make the user choose the duration of the workshop they want to propose

**Comment by ivarni** [comment]
Compromised at having 3 different types of workshops, each with their own duration.
